#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 5424026
#
Name     : perl-Image-Info
Version  : 1.45
Release  : 32
URL      : https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Image-Info-1.45.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Image-Info-1.45.tar.gz
Summary  : 'Extract meta information from image files'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Image-Info-perl = %{version}-%{release}
Requires: perl(Image::Xbm)
Requires: perl(Image::Xpm)
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This Perl extension allows you to extract meta information from various
types of image files. The following file formats are supported:

%package dev
Summary: dev components for the perl-Image-Info package.
Group: Development
Provides: perl-Image-Info-devel = %{version}-%{release}
Requires: perl-Image-Info = %{version}-%{release}

%description dev
dev components for the perl-Image-Info package.


%package perl
Summary: perl components for the perl-Image-Info package.
Group: Default
Requires: perl-Image-Info = %{version}-%{release}

%description perl
perl components for the perl-Image-Info package.


%prep
%setup -q -n Image-Info-1.45
cd %{_builddir}/Image-Info-1.45
pushd ..
cp -a Image-Info-1.45 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Bundle::Image::Info::Everything.3
/usr/share/man/man3/Bundle::Image::Info::PNG.3
/usr/share/man/man3/Bundle::Image::Info::SVG.3
/usr/share/man/man3/Bundle::Image::Info::XBM.3
/usr/share/man/man3/Bundle::Image::Info::XPM.3
/usr/share/man/man3/Image::Info.3
/usr/share/man/man3/Image::Info::AVIF.3
/usr/share/man/man3/Image::Info::BMP.3
/usr/share/man/man3/Image::Info::GIF.3
/usr/share/man/man3/Image::Info::ICO.3
/usr/share/man/man3/Image::Info::PPM.3
/usr/share/man/man3/Image::Info::SVG.3
/usr/share/man/man3/Image::Info::TIFF.3
/usr/share/man/man3/Image::Info::WBMP.3
/usr/share/man/man3/Image::Info::XBM.3
/usr/share/man/man3/Image::Info::XPM.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
